SET IDENTITY_INSERT [dbo].[Envios] ON
INSERT INTO [dbo].[Envios] ([Id], [NumeroTracking], [PesoPaquete], [Estado], [ClienteId], [FuncionarioId], [Discriminator], [AgenciaId], [DireccionPostal], [EntregaEficiente]) VALUES (75, N'TRK001', 5, 1, 19, 15, N'Comun', 7, NULL, NULL)
INSERT INTO [dbo].[Envios] ([Id], [NumeroTracking], [PesoPaquete], [Estado], [ClienteId], [FuncionarioId], [Discriminator], [AgenciaId], [DireccionPostal], [EntregaEficiente]) VALUES (76, N'TRK002', 4, 1, 20, 16, N'Comun', 8, NULL, NULL)
INSERT INTO [dbo].[Envios] ([Id], [NumeroTracking], [PesoPaquete], [Estado], [ClienteId], [FuncionarioId], [Discriminator], [AgenciaId], [DireccionPostal], [EntregaEficiente]) VALUES (77, N'TRK003', 6, 1, 21, 17, N'Comun', 9, NULL, NULL)
INSERT INTO [dbo].[Envios] ([Id], [NumeroTracking], [PesoPaquete], [Estado], [ClienteId], [FuncionarioId], [Discriminator], [AgenciaId], [DireccionPostal], [EntregaEficiente]) VALUES (78, N'TRK004', 8, 0, 22, 18, N'Comun', 10, NULL, NULL)
INSERT INTO [dbo].[Envios] ([Id], [NumeroTracking], [PesoPaquete], [Estado], [ClienteId], [FuncionarioId], [Discriminator], [AgenciaId], [DireccionPostal], [EntregaEficiente]) VALUES (79, N'TRK005', 3, 0, 24, 23, N'Comun', 11, NULL, NULL)
INSERT INTO [dbo].[Envios] ([Id], [NumeroTracking], [PesoPaquete], [Estado], [ClienteId], [FuncionarioId], [Discriminator], [AgenciaId], [DireccionPostal], [EntregaEficiente]) VALUES (80, N'TRK006', 7, 1, 19, 15, N'Urgente', NULL, 1000, 1)
INSERT INTO [dbo].[Envios] ([Id], [NumeroTracking], [PesoPaquete], [Estado], [ClienteId], [FuncionarioId], [Discriminator], [AgenciaId], [DireccionPostal], [EntregaEficiente]) VALUES (81, N'TRK007', 4, 1, 20, 16, N'Urgente', NULL, 1001, 1)
INSERT INTO [dbo].[Envios] ([Id], [NumeroTracking], [PesoPaquete], [Estado], [ClienteId], [FuncionarioId], [Discriminator], [AgenciaId], [DireccionPostal], [EntregaEficiente]) VALUES (82, N'TRK008', 2, 0, 21, 17, N'Urgente', NULL, 1002, 0)
INSERT INTO [dbo].[Envios] ([Id], [NumeroTracking], [PesoPaquete], [Estado], [ClienteId], [FuncionarioId], [Discriminator], [AgenciaId], [DireccionPostal], [EntregaEficiente]) VALUES (83, N'TRK009', 9, 0, 22, 18, N'Urgente', NULL, 1003, 1)
INSERT INTO [dbo].[Envios] ([Id], [NumeroTracking], [PesoPaquete], [Estado], [ClienteId], [FuncionarioId], [Discriminator], [AgenciaId], [DireccionPostal], [EntregaEficiente]) VALUES (84, N'TRK010', 5, 0, 24, 23, N'Urgente', NULL, 1004, 0)
SET IDENTITY_INSERT [dbo].[Envios] OFF
